version: "3.3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4567-4600:4567-4600"
      - "8080:8080"
    environment:
      - SERVICES=sqs,s3,dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    networks:
      - localstack_default
    volumes:
      - '/tmp/localstack:/tmp'
networks:
  localstack_default:
    driver: bridge
    ipam:
      driver: default

